### PR TITLE
[ADD] description to for text in credit_notes

### PR DESCRIPTION
**Pull request by victor-champonnois**
## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=9204&model=project.task&view_type=form&menu_id=

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Review by robinkeunen — APPROVED** [review]

**Review by robinkeunen — CHANGES_REQUESTED** [review]
I don't think this is the way to format code blocks in `.rst`: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

**Comment by victor-champonnois** [comment]
@robinkeunen fixed

**Comment by robinkeunen** [comment]
@victor-champonnois the pre-commit error is the same I had on all other repositories. It was fixed on the OCA. @carmenbianca do we have something to do on our repositories ?

**Comment by victor-champonnois** [comment]
@robinkeunen can you re-review ?

**Review by robinkeunen — APPROVED** [review]

**Pull request merged**
