### PR TITLE
[16.0][MIG] foodhub_custom

### PR DESCRIPTION
**Pull request by victor-champonnois**
https://gestion.coopiteasy.be/web#id=10928&action=475&active_id=492&model=project.task&view_type=form&menu_id=

### CODE REVIEW

**Comment by victor-champonnois** [comment]
Test don't work because it depends on sale_order_volume : I wait for https://github.com/coopiteasy/addons/pull/305 to be merged and then I'll rebase

**Review by polchampion — CHANGES_REQUESTED** [review]
Functional test 1

- [ ]  add order volume to delivery slip --> **got an error attempting to print delivery slips - see traceback below**
- [ ] add price information on delivery slip
- [x] link picking to sale order --> **though I think it should read : "display sale order number on picking"**, because it's not an internal link
- [ ] link moves and move lines to sale order line **--> how? not clear where**
- [ ] hide product terms from website sale product page **what are "product terms"?**
- [ ] add a small text in customer credit notes document. This was done directly in the Odoo interface, by creating a view `report_invoice_document_custom_refund` **NOK - [see example](https://odoo16.main.test.srv.coopiteasy.be/web?db=16-test-wholesale#cids=1&menu_id=123&action=217&model=account.move&view_type=form&id=4)**


- Error printing the [delivery slip](https://odoo16.main.test.srv.coopiteasy.be/web?db=16-test-wholesale#id=5&cids=1&menu_id=244&action=319&active_id=5&model=stock.picking&view_type=form):
```RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "<794>", line 1853, in template_794
  File "<794>", line 1835, in template_794_content
  File "<794>", line 1818, in template_794_t_call_0
  File "<794>", line 1388, in template_794_t_call_1
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_qweb.py", line 2383, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_qweb_fields.py", line 496, in record_to_html
    return super(MonetaryConverter, self).record_to_html(record, field_name, options)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_qweb_fields.py", line 121, in record_to_html
    return False if value is False else self.value_to_html(value, options=options)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_qweb_fields.py", line 448, in value_to_html
    fmt = "%.{0}f".format(display_currency.decimal_places)
AttributeError: 'str' object has no attribute 'decimal_places'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo16/src/odoo/addons/web/controllers/report.py", line 113, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/home/odoo16/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo16/src/oca/reporting-engine/report_xlsx_helper/controllers/main.py", line 52, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/home/odoo16/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo16/src/oca/reporting-engine/report_xlsx/controllers/main.py", line 49, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/home/odoo16/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo16/src/odoo/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/home/odoo16/src/odoo/addons/account/models/ir_actions_report.py", line 58, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 819, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo16/src/odoo/addons/account_edi_ubl_cii/models/ir_actions_report.py", line 58, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo16/src/odoo/addons/account_edi/models/ir_actions_report.py", line 14, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo16/src/odoo/addons/account/models/ir_actions_report.py", line 20, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 708, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, res_ids_wo_stream, data=data)[0]
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 896, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 623, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/home/odoo16/src/odoo/addons/website/models/ir_ui_view.py", line 419, in _render_template
    return super()._render_template(template, values=values)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 2125, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/home/odoo16/src/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo16/src/odoo/odoo/addons/base/models/ir_qweb.py", line 581, in _render
    result = ''.join(rendering)
  File "<799>", line 65, in template_799
  File "<799>", line 52, in template_799_content
  File "<794>", line 1859, in template_794
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'str' object has no attribute 'decimal_places'
Template: stock.report_delivery_document
Path: /t/t/t/div/t[1]/div[1]/div/table/tr[1]/td[2]/span
Node: <span t-field="sale_order.amount_untaxed" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: &quot;so.pricelist_id.currency_id&quot;}"/>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://odoo16.main.test.srv.coopiteasy.be/web/assets/299-1ea9eaa/web.assets_backend.min.js:985:274
    makeErrorFromResponse@https://odoo16.main.test.srv.coopiteasy.be/web/assets/299-1ea9eaa/web.assets_backend.min.js:989:163
    configureBlobDownloadXHR/xhr.onload/decoder.onload@https://odoo16.main.test.srv.coopiteasy.be/web/assets/299-1ea9eaa/web.assets_backend.min.js:976:7```

**Comment by victor-champonnois** [comment]
> Functional test 1
> 
>     * [ ]   add order volume to delivery slip --> **got an error attempting to print delivery slips - see traceback below**
fixed
> 
>     * [ ]  add price information on delivery slip
> 
>     * [x]  link picking to sale order --> **though I think it should read : "display sale order number on picking"**, because it's not an internal link

Do you mean the "source document" in the picking form ? This is a standard feature. 
The functionality mentioned here is purely technical, it should not be mentioned.  -> I removed it from the description. 
> 
>     * [ ]  link moves and move lines to sale order line **--> how? not clear where**
This is a technical aspect of the module. It should not be included in the description. I removed it. 
> 
>     * [ ]  hide product terms from website sale product page **what are "product terms"?**
This : 
image

> 
>     * [ ]  add a small text in customer credit notes document. This was done directly in the Odoo interface, by creating a view `report_invoice_document_custom_refund` **NOK - [see example](https://odoo16.main.test.srv.coopiteasy.be/web?db=16-test-wholesale#cids=1&menu_id=123&action=217&model=account.move&view_type=form&id=4)**

It was done in the interface, that's why it was not there. To avoid forgetting about this I implemented it in the module. It should work now.

**Comment by polchampion** [comment]
Functional test 2
@victor-champonnois 

- [ ]  add order volume to delivery slip --> **I still get the same error attempting to print delivery slips, even after updating `base`**
- [ ] add price information on delivery slip **-  unable to check because of the error above**
- [x] hide product terms from website sale product page **OK, however it looks like you can remove this simply through the website editor**
- [ ] add a small text in customer credit notes document, by creating a view `report_invoice_document_custom_refund` **I still do not see it, nor can find the view**

**Comment by victor-champonnois** [comment]
@polchampion arg sorry I thought you were going to test on the runboat, so I did not deploy to test. It's done now. Sorry again for the confusion.

**Comment by polchampion** [comment]
> @polchampion arg sorry I thought you were going to test on the runboat, so I did not deploy to test. It's done now. Sorry again for the confusion.

@victor-champonnois There is not yet a runboat on our private repo, sadly - or am I missing something?

**Comment by victor-champonnois** [comment]
@polchampion No you're right :)

**Review by polchampion — APPROVED** [review]
Functional test 3

- [x] adds order volume to delivery slip
- [x] adds price information on delivery slip
- [x] hides product terms from website sale product page **OK, however it looks like you can remove this simply through the website editor**
- [x] adds a small text in customer credit notes document, by creating a view `report_invoice_document_custom_refund`

**Review by carmenbianca — APPROVED** [review]
LGTM

**Pull request merged**
