### PR TITLE
12.0 provelo manager data access

### PR DESCRIPTION
**Pull request by victor-champonnois**
Task : https://gestion.coopiteasy.be/web#id=7822&view_type=form&model=project.task&action=479

- Allow manager to access his/her employees data (not only n-1 but n-*)
- Allow for the special case where a user is linked to multiple employees using `.mapped("id")` instead of `.id`

### CODE REVIEW

**Review by huguesdk — COMMENTED** [review]
might be overkill (especially for a custom module, need to ask analysts whether we have time for this), but adding at least one test to check one of these rules would be nice. (edit: hum: isn’t it arrogant to request tests when i didn’t write any in the first place? ☺)

also, please run `pre-commit` on the xml file, there is a line that is too long.

edit: well done with the use of `child_of`, it’s much cleaner!

**Comment by victor-champonnois** [comment]
@huguesdk 
Thx for your feedback, I asked the analyst about finding time to add a test;
I ran pre-commit (sorry, its not the first time it happens, I need to fix my config)

**Comment by victor-champonnois** [comment]
@huguesdk Tests added. 
About the tests: there some tests about whether a user can access data, so it is a test about not raising an error. 
If the test fails, it will not declare a failure, but an error. There are some discussions about whether this is ok [here](https://stackoverflow.com/questions/4319825/python-unittest-opposite-of-assertraises) and [here](https://stackoverflow.com/questions/20274987/how-to-use-pytest-to-check-that-error-is-not-raised?noredirect=1&lq=1) but there does not seem to be a consensual way to deal with this.

**Comment by huguesdk** [comment]
great, thanks! i think that the tests you wrote to check that it works (trying to access data) is exactly what’s needed.

**Review by huguesdk — APPROVED** [review]

**Pull request merged**
