### PR TITLE
[16.0][MIG]] foodhub_custom_product_kanban_view

### PR DESCRIPTION
**Pull request by victor-champonnois**
https://gestion.coopiteasy.be/web#id=10929&action=475&active_id=568&model=project.task&view_type=form&menu_id=536

### CODE REVIEW

**Comment by victor-champonnois** [comment]
@polchampion deployed to test

**Comment by victor-champonnois** [comment]
I don't understand the pre-commit error, seems not related to this code ?

**Review by robinkeunen — APPROVED** [review]
LGTM.

suggestion, non-blocking : first 3 commits (even 6 IMO but Carmen would disagree) could be squashed.

**Comment by victor-champonnois** [comment]
@robinkeunen pre-commit fixed and commits squashed.

**Comment by robinkeunen** [comment]
Great, I rebased on _fixed_ 16.0. You'll need to reset your branch to thus one before changing this branch further.

**Review by polchampion — APPROVED** [review]
successful functional test

Adapts the product kanban view :
- [x] Removes the *Quantity on Hand* from the product kanban view.
- [x] Adds *Description for Customer* on the product kanban view.

@victor-champonnois note that I didn't find how to display the quantity on hand on a clean db, but I could test the module's behaviour on a db where the quantity on hand was already displayed.

**Pull request merged**
